subsonic:
  #build: .
  image: druminik/lms-server
  restart: always
  net: "bridge"
  ports:
  - "9000:9000"
  - "9090:9090"
  - "3483:3483"
  volumes:
  - "/media/music:/var/music:rw"
  container_name: lms-server
